server:
  port: 8081

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/core_pay
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none

integration:
  client:
    products:
      uri: http://localhost:8080
      connectionTimeout: 10s
      readTimeout: 10s
      get-all-path: /api/product
      execute-payment-path: /api/product/{accountNumber}/pay